#!/usr/bin/env bash
#Install haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 145835-web-01 100.24.72.61:80 check\n\tserver 145835-web-02 100.26.122.185:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
