#!/usr/bin/env bash
# displays Best School 10 times.

DISPLAY=0
while [ $DISPLAY -lt 11 ]
do
    if [ $DISPLAY = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((DISPLAY+=1))
done
