#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 35.153.78.254
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
